### ISSUE TITLE
UI/API: cant stop deleted runs in administrative view

### ISSUE THREAD

**Issue by rssk** [MRN-Code/coinstac#1253]
Trying to stop a deleted run gives you:
```
[0]   "TypeError: Cannot read properties of null (reading 'id')",
[0]   '    at EventEmitter.runChanged (/Users/ross/coins/coinstac/packages/coinstac-api-server/src/data/subscriptions/index.js:149:14)',
[0]   '    at EventEmitter.emit (node:events:520:28)',
[0]   '    at updateRunState (/Users/ross/coins/coinstac/packages/coinstac-api-server/src/data/resolvers.js:1276:20)',
[0]   '    at runMicrotasks (<anonymous>)',
[0]   '    at processTicksAndRejections (node:internal/process/task_queues:96:5)'
```

**Comment by dylanmartin** [comment]
What steps would I take to re create this bug?
Starting a run and deleting it appears to stop the run as well.
