### ISSUE TITLE
VBM regression reading input options

### ISSUE THREAD

**Issue by spanta28** [MRN-Code/coinstac#1443]
"Pipeline error from pipeline 6306c480d4e7f0320cc26aa9 user: test1\n Error details: Computation failed with exitcode 1 and stderr Traceback (most recent call last):\n File "/computation/scripts/local.py", line 187, in \n sys.stdout.write(local_0(PARAM_DICT))\n File "/computation/scripts/local.py", line 31, in local_0\n threshold = input_["threshold"]\nKeyError: 'threshold'\n"

Unless I change the input options , the computation wont run. If I change all the values then it runs successfully.

**Comment by hvgazula** [comment]
@spanta28 Does it mean the default values are not read/loaded correctly?
