### ISSUE TITLE
Vault data combined with local data gives error

### ISSUE THREAD

**Issue by spanta28** [MRN-Code/coinstac#1601]
## Task Description
Used the master coinstac latest code. Created consortia, added Trends VBM vault, made myself(spanta) also as active user and mapped local data with common covariates from the vault and local data. Made sure the covariates for both vault and local data are in same datatype format. Ran regression VBM and it gave this error. Tried the same with CMI VBM vault as well and it gave same error. Name of the consortia's if you want to look at the pipeline setup. Tagging @pixelsaurus if you have any comments on the pipeline setup:
TrendsVault_local_vbm
CMIVault_vbm_local

This was not the case before, so I am not sure if there is a code difference between VBM Vault and regular VBM regression that is leading to this or something. Need this for Vault's paper results:

Results Object:
--
null
*Output Type not defined in Compspec.

Pipeline error from central node Error details: Computation failed with exitcode 1 and stderr Traceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/coinstac/__init__.py", line 23, in _func output = await _asyncio.get_event_loop().run_in_executor(None, remote, msg['data']) File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run result = self.fn(*self.args, **self.kwargs) File "/computation/scripts/remote.py", line 265, in start return remote_0(PARAM_DICT) File "/computation/scripts/remote.py", line 43, in remote_0 covar_keys, unique_count = return_uniques_and_counts(df) File "/computation/scripts/remote_ancillary.py", line 29, in return_uniques_and_counts flat_list = [item for sublist in row for item in sublist] File "/computation/scripts/remote_ancillary.py", line 29, in <listcomp> flat_list = [item for sublist in row for item in sublist] TypeError: 'float' object is not iterable
Error: Computation failed with exitcode 1 and stderr Traceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/coinstac/__init__.py", line 23, in _func output = await _asyncio.get_event_loop().run_in_executor(None, remote, msg['data']) File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run result = self.fn(*self.args, **self.kwargs) File "/computation/scripts/remote.py", line 265, in start return remote_0(PARAM_DICT) File "/computation/scripts/remote.py", line 43, in remote_0 covar_keys, unique_count = return_uniques_and_counts(df) File "/computation/scripts/remote_ancillary.py", line 29, in return_uniques_and_counts flat_list = [item for sublist in row for item in sublist] File "/computation/scripts/remote_ancillary.py", line 29, in <listcomp> flat_list = [item for sublist in row for item in sublist] TypeError: 'float' object is not iterable at /usr/local/src/coinstac/packages/coinstac-manager/src/services/serviceFunction.js:258:21 at runMicrotasks (<anonymous>) at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by spanta28** [comment]
@hvgazula any thoughts here? Please reply at your available time, I don't mean to flood you on a consistent basis. I think once we get through these core features implementation and have the new GRA working , wee can have him do improvements.

**Comment by spanta28** [comment]
@rssk This is the issue
